2025-03-07 10:34:16,336 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (352,)
Traceback (most recent call last):
  File "E:\anaconda\anaconda\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1154, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 600, in numpy.random._common.cont
  File "_common.pyx", line 517, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 741, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (100, 352) and arg 1 with shape (100, 8, 44).
2025-03-07 10:34:54,193 - pyswarms.single.global_best - INFO - Optimize for 200 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2025-03-07 10:34:56,150 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 2060.0, best pos: [ 8.51674531  2.77404934  1.15654807  9.78479037 18.44083016  5.55634337
  3.83554549  5.22368825]
2025-03-07 10:35:36,591 - pyswarms.single.global_best - INFO - Optimize for 200 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2025-03-07 10:35:38,393 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 2310.0, best pos: [ 7.14744311  0.88368826 10.63989782  1.93809666 15.91686734 24.82629797
  4.32797436  0.47679392]
2025-03-07 10:36:28,693 - pyswarms.single.global_best - INFO - Optimize for 200 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2025-03-07 10:36:30,510 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 2271.0, best pos: [ 4.44700025  6.27893999  2.63308416 20.20588589 28.35542219 15.0441569
  0.3116346   0.92910313]
